language: minimal
dist: xenial
services:
  - docker
before_install:
  - curl https://raw.githubusercontent.com/plicease/cip/main/bin/travis-bootstrap | bash
  - cip before-install
install:
  - cip diag
  - cip install
script:
  - cip script
jobs:
  include:
    - env: CIP_TAG=5.32-buster-arm64v8
      arch: arm64
    - env: CIP_TAG=5.32 ALIEN_WASMTIME_VERSION=dev
    - env: CIP_TAG=5.18 ALIEN_WASMTIME_VERSION=dev
  allow_failures:
    - env: CIP_TAG=5.32 ALIEN_WASMTIME_VERSION=dev
    - env: CIP_TAG=5.18 ALIEN_WASMTIME_VERSION=dev

branches:
  only:
    - main
cache:
  directories:
    - "$HOME/.cip"


